# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FreeRealEstate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FreeRealEstate

  target 'FreeRealEstate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FreeRealEstateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FreeRealEstate-tvOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FreeRealEstate-tvOS

  target 'FreeRealEstate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
